### ISSUE TITLE
Something strange with the result of export

### ISSUE THREAD

**Issue by hezixinshellingfordf** [eckertzhang/HumanRef#6]
I really appreciate the work. 
When I run "python run.py --config configs/humanref.yaml --export --gpu 0 image_path='./data/Results_ECON/test5_1/econ/imgs_crop/test5_1_0_rgba.png' ",I got a really strange output. 
I wonder how to fix it 🙇‍♂.
![截图 2024-09-04 17-28-32](https://github.com/user-attachments/assets/595b9409-b3c3-4852-9e3d-ad26cdb068db)

**Comment by eckertzhang** [comment]
What is shown in the picture does not seem to be the output of HumanRef. Did you convert the SDF into a mesh?

**Comment by hezixinshellingfordf** [comment]
I change the value of resume manually then it works well. thank you !
